version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pg
      POSTGRES_DB: vecdb
    ports:
      - "5432:5432"
  backend:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    command: uvicorn backend.app.main:app --host 0.0.0.0 --port 8000
    environment:
      DATABASE_URL: postgresql://pg:pg@db:5432/vecdb
    volumes:
      - .:/workspace
    depends_on:
      - db
    ports:
      - "8000:8000"
